### DISCUSSION TITLE
How would i go about playing around with editing the theme?

### DISCUSSION THREAD

**Discussion by Jacob-Branch** [roundcube/roundcubemail-docker#193] [Q&A]
Hello! 👋

I've been trying to set up a way for me to easily modify the theme of the roundcube mail app, so i can figue out what i can and cant do regarding changes to the UI. Ive so far figured out how to go about eding the files using docker volumes, but i ran in to an issue, that i dont know in which diractory i should be actually editing the css/less files.

So my question is: What diractory/path is being rendered and/or which one would i have to edit to see the results in my browser?

my docker-compose code is here :
```

version: '1'
name: "roundcube"

services:
  roundcubemail:
    image: "roundcubeorg/roundcubemail:latest-apache"
    ports:
      - "80:80"
    volumes:
      - ./cont/html/public_html/skins/elastic:/var/www/html/public_html/skins/elastic

    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: ssl://imap.gmail.com
      ROUNDCUBEMAIL_DEFAULT_PORT: 993
      ROUNDCUBEMAIL_SMTP_SERVER: ssl://smtp.gmail.com

```
