### ISSUE TITLE
Couldn't change the configuration for managesieve

### ISSUE THREAD

**Issue by Danissss** [roundcube/roundcubemail-docker#116]
Hi, I have read the issue #79, and follow the steps but the roundcube is still trying to connect to localhost rather than desired one.

Here is my managesieve.inc.php at config/
```php
$config['managesieve_host'] = 'mail.sample.ca';
```

Here is the docker-compose I ran:
```yaml
version: '3.6'

services:
        roundcubemail:
                image: roundcube/roundcubemail:latest
                container_name: roundcubemail
                volumes:
                        - ./config/:/var/roundcube/config
                ports:
                        - 8000:80
                environment:
                        - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.sample.ca
                        - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.sample.ca
                        - ROUNDCUBEMAIL_PLUGINS=managesieve

```

I checked the `/var/roundcube/config/` inside container, and the managesieve.inc.php exist; but `/var/www/html/plugins/managesieve/config.inc.php.dist` still use `$config['managesieve_host'] = 'localhost';`

Am I missing something?

Thanks!
