### ISSUE TITLE
Invisible sieve filters (After reinstall)

### ISSUE THREAD

**Issue by UbioZur** [roundcube/roundcubemail-docker#153]
I had to do a full reinstall of my setup (database and RC docker). I backed up the config/plugins/skins folder as well as the database of course.

No issue to connect and access the webmail after the reinstall. Except for 1:

All my previously setup sieve filters are invisible! As in, they still works, they still filters my emails correctly, but the filter list in the settings is empty. So I cannot modify or remove any.

Any pointer to help me fix that? Any ideas on what I should add to my backups to avoid it in the future? I am definitly not a pro in sieve nor docker.

Expected: Seeing the Sieve filters that are used by the account.

RC: 1.4.11 roundcube/roundcubemail:latest
MariaDB: 10.6.4 mariadb:10.6.4

Docker-compose section:
```
roundcube:
        container_name: roundcube
        image: "roundcube/roundcubemail:latest"
        restart: unless-stopped
        networks:
            proxy:
                ipv4_address: 172.42.0.21
        dns:
            - 172.42.0.2
        hostname: roundcube
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ${HOME}/internal/roundcube/data:/var/roundcube/config
            # Third party plugin and skins (https://plugins.roundcube.net/#/)
            - ${HOME}/internal/roundcube/plugins:/var/www/html/plugins/
            - ${HOME}/internal/roundcube/skins:/var/www/html/skins/
        env_file:
            - .rc.env
        environment:
            - PUID=1000
            - PGID=1000
            - ROUNDCUBEMAIL_SKIN=elastic
            - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=15M
            # builtin plugins: https://github.com/roundcube/roundcubemail/tree/master/plugins
            - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload,managesieve
        labels:
            - com.centurylinklabs.watchtower.monitor-only
```
