### ISSUE TITLE
Oauth(KeyCloak) Users Login Failed

### ISSUE THREAD

**Issue by arunodhayam10d** [roundcube/roundcubemail-docker#158]
Hi guys... I have installed Roundcube and Keycloak in docker. I have integrated Keycloak with Roundcube also I have done the IMAP and SMTP configurations. I can able to login with Roundcube using IMAP mail server users. 
But I can't log in With Keycloak created users. It shows login failed.
My keycloak hosted under https://keycloak.domain1.com
My Roundcube hosted under https://roundcube.domain2.com
**Note:  Both Domains are diffrent**
Example: 
IMAP server has one user that username: **Admin**. I can able to login
KEYCLOAK(Oauth) created one user that username: **roundcube**. I can't login 

```
version: '2'

services:
  roundcubedb:
    image: mysql:5.7
    container_name: roundcubedb_1.5
   restart: unless-stopped
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 34013:5432
      - 33009:3306
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail

  roundcubemail:
    image: roundcube/roundcubemail:1.5-beta-apache
    container_name: roundcubemail_1.5
    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - ./www:/var/www/html
    ports:
      - 9005:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mailserver.domain.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=993  
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://mailserver.domain.com
      - ROUNDCUBEMAIL_SMTP_PORT=465  
```
This is my docker-compose file.

- Rouncdube Auth config: 
- Path: /www/config/defaults.inc.php

```
$config['oauth_provider'] = 'keycloak';
$config['oauth_provider_name'] = 'SSO';
$config['oauth_client_id'] = "roundcube";
$config['oauth_client_secret'] = "<the secret I got from keycloak for this client>";
$config['oauth_auth_uri'] = "https://my.keycloak.host/auth/realms/test_saml/protocol/openid-connect/auth?";
$config['oauth_token_uri'] = "https://my.keycloak.host/auth/realms/test_saml/protocol/openid-connect/token";
$config['oauth_identity_uri'] = null;
$config['oauth_verify_peer'] = true;
$config['oauth_scope'] = "email profile roles openid";
$config['oauth_auth_parameters'] = ['access_type' => 'offline'];
$config['oauth_identity_fields'] = null;
$config['oauth_login_redirect'] = false;
```

- Roundcube log config:
- Path: /www/config/defaults.inc.php

All the debug options in roundcube are set to true except one:
```
$config['per_user_logging'] = false;
$config['smtp_log'] = true;
$config['log_logins'] = true;
$config['session_debug'] = true;
$config['sql_debug'] = true;
$config['imap_debug'] = true;
$config['ldap_debug'] = true;
$config['smtp_debug'] = true;
$config['memcache_debug'] = true;
$config['apc_debug'] = true;
$config['redis_debug'] = true;
```
Keycloak roundcube client config (it's more than possible that the problem comes from her as I'm quite new to SSO and very new to OpenID connect):
SETTINGS :

  ```
Client ID : rouncube
  Name : Roundcube
  Enabled: ON
  Consent Required : OFF
  Client Protocol : openid connect
  Access Type : confidential
  Standard Flow Enabled : ON
  Implicit Flow Enabled : OFF
  Direct Access Grants Enabled : ON
  Service Accounts Enabled : ON
  Authorization Enabled : ON
  Root URL : https://my.roundcube.host/
  Valid Redirect URI : https://my.roundcube.host/*
  Web Origins : https://my.roundcube.host
```

CLIENT SCOPE :

  ```
Assigned Default Client Scopes : email / profile / roles / web-origins
  Assigned Optional Client Scopes : address / microprofile-jwt / offline_access / phone
```

MAPPERS :

  ```
Client Host 
    Mapper Type: User Session Note
    User Session Note : clientHost
    Token Claim Name: clientHost
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON

  Client IP Address
    Mapper Type: User Session Note
    User Session Note : clientAddress
    Token Claim Name: clientAddress
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON

  Client ID
    Mapper Type: User Session Note
    User Session Note : clientId
    Token Claim Name: clientId
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON

  Mail
    Mapper Type: User Property
    Property : email
    Token Claim Name: email
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON
    Add to userinfo : ON

  Uid
    Mapper Type: User Property
    Property : usenrame
    Token Claim Name: uid
    Claim JSON Type: String
    Add to ID token : ON
    Add to access token : ON
    Add to userinfo : ON

SCOPE

  Full Scope Allowed : ON

```
please help with this??
