### ISSUE TITLE
Fresh installation mssing Spoofchecker

### ISSUE THREAD

**Issue by snooops** [roundcube/roundcubemail-docker#172]
Fresh installation using `docker-compose` is throwing an error after successful login:

`PHP Fatal error:  Uncaught Error: Class 'Spoofchecker' not found in /var/www/html/program/lib/Roundcube/rcube_spoofchecker.php:50\nStack trace:\n#0 /var/www/html/program/actions/mail/index.php(1400): `

my compose file:
```
version: "3"

services:
  webmail:
    image: roundcube/roundcubemail:latest
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mailserver
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mailserver
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
      - ROUNDCUBEMAIL_ASPELL_DICTS=de,en
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.entrypoints=http"
      - "traefik.http.routers.roundcube.rule=Host(`roundcube`)"  ## Hier eure Domain eingeben ##
      - "traefik.http.middlewares.roundcube-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.roundcube.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.roundcube-secure.entrypoints=https"
      - "traefik.http.routers.roundcube-secure.rule=Host(`roundcube`)" ## Hier eure Domain eingeben ##
      - "traefik.http.routers.roundcube-secure.tls=true"
      - "traefik.http.routers.roundcube-secure.tls.certresolver=http"
      - "traefik.http.routers.roundcube-secure.service=roundcube"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.roundcube-secure.middlewares=secHeaders@file"
    restart: always
    networks:
      - proxy
    volumes:
      - ./roundcube/config:/var/roundcube/config/
      - ./roundcube/php-config:/usr/local/etc/php/conf.d/
      - ./db/sqlite:/var/roundcube/db
   
networks:
  proxy:
    external: true
```
