### ISSUE TITLE
Additional configuration options not being read into default PHP file

### ISSUE THREAD

**Issue by es9o** [roundcube/roundcubemail-docker#174]
I'm using the docker-compose command below to (successfully) build an instance of Roundcube. 

Within the volume I have mounted under '/var/roundcube/config' I also have a config.inc.php file (also provided below) that I've added some additional configuration options to be loaded into Roundcube that weren't available via environmental variables.

However, upon restarting the container, these additional configuration options are not loaded into any of the config files located at /var/www/html.

What am I doing wrong that my additional configuration options aren't being loaded into Roundcube?

```
  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    restart: unless-stopped
    environment: 
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 100M
      ROUNDCUBEMAIL_DEFAULT_HOST: ${ROUNDCUBE_IMAP_HOST}
      ROUNDCUBEMAIL_DEFAULT_PORT: ${ROUNDCUBE_IMAP_PORT}
      ROUNDCUBEMAIL_SMTP_SERVER: ${ROUNDCUBE_SMTP_HOST}
      ROUNDCUBEMAIL_SMTP_PORT: ${ROUNDCUBE_SMTP_PORT}
      ROUNDCUBEMAIL_PLUGINS: archive,zipdownload
      ROUNDCUBEMAIL_SKIN: elastic
      ROUNDCUBEMAIL_DB_TYPE: pgsql
      ROUNDCUBEMAIL_DB_HOST: ${ROUNDCUBE_DB_HOST}
      ROUNDCUBEMAIL_DB_PORT: ${ROUNDCUBE_DB_PORT}
      ROUNDCUBEMAIL_DB_USER: ${ROUNDCUBE_DB_USER}
      ROUNDCUBEMAIL_DB_PASSWORD: ${ROUNDCUBE_DB_PASSWORD}
      ROUNDCUBEMAIL_DB_NAME: ${ROUNDCUBE_DB_DATABASE}
    volumes:
      - ${APPDATA}/roundcube/config:/var/roundcube/config
      - ${APPDATA}/roundcube/www:/var/www/html
      - ${MOUNT}/roundcube:/tmp/roundcube-temp
    depends_on:
      - postgres
    networks:
      - nginx
      - postgres
```

```
<?php

$config = [];

// ----------------------------------
// SMTP
// ----------------------------------

$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

// ----------------------------------
// SYSTEM
// ----------------------------------

$config['max_message_size'] = '100M';
$config['temp_dir_ttl'] = '48h';

// ----------------------------------
// PLUGINS
// ----------------------------------

$config['plugins'] = [
    'archive',
    'zipdownload',
    'carddav'
];

// ----------------------------------
// USER INTERFACE
// ----------------------------------

$config['message_sort_col'] = 'date';
$config['message_sort_order'] = 'DESC';
```
