### ISSUE TITLE
Custom config not persist? config.docker.inc.php

### ISSUE THREAD

**Issue by hermesalvesbr** [roundcube/roundcubemail-docker#217]
![Captura de tela de 2023-05-20 21-20-35](https://github.com/roundcube/roundcubemail-docker/assets/379850/c7cde7c0-ff5c-459b-9929-db6e8a0b7c85)

I put the html to persist, in desperation I put html/config too.

Then I modify the config.docker.inc.php , when I restart the container, everything is lost. I already checked on my server, and the files are persisted. I've also tried to edit inside the container (docker exec -it) and also directly on the server (nvim config.docker.inc.php)

The settings work beautifully, but when restarting the container, it doesn't work anymore. What am I doing wrong?

Should I inform new configs in the ENV of the container?

**Comment by hermesalvesbr** [comment]
I saw this when reboot the container: 

`Write Docker config to /var/www/html/config/config.docker.inc.php`

How can block this?

**Comment by kwisatz** [comment]
> I saw this when reboot the container:
> 
> `Write Docker config to /var/www/html/config/config.docker.inc.php`
> 
> How can block this?

You probably shouldn't. Custom configuration goes into custom.php 

```yaml
  rcapp:
    image: roundcube/roundcubemail:latest-apache
    restart: always
    depends_on:
      - rcdb
    volumes:
      - ./data/conf/rcapp:/var/roundcube/config:ro,Z
    environment:
     […]
```
