### ISSUE TITLE
ROUNDCUBEMAIL_REQUEST_PATH does not work with latest-apache

### ISSUE THREAD

**Issue by zyberwoof** [roundcube/roundcubemail-docker#265]
I'm using a setup similar to the following:
https://github.com/roundcube/roundcubemail-docker/blob/master/examples/docker-compose-mysql.yaml

When initially deployed, everything works as expected.  There are no issues.  

As soon as I add the ROUNDCUBEMAIL_REQUEST_PATH=/roundcube environmental variable to my compose file, things break.  At this point...

- http://hostname.com still brings the user to the normal login page.
- If a user logs in via http://hostname.com, the browser redirects to http://hostname.com/roundcube/?_task=login and a 403 Forbidden response is given.
- Navigating directly to http://hostname.com/roundcube/ also returns a 403 Forbidden response.

I think I have found the issue at a high level.  When viewing the logs (docker-compose logs --follow), the first 2 entries say the following:

```
roundcubemail not found in /var/www/html - copying now...
Complete! ROUNDCUBEMAIL has been successfully copied to /var/www/html
```

I'm guessing that in order for http://hostname.com/roundcube to work, Apache wants everything to live at /var/www/html/roundcube.

I think that one fix would be to dynamically adjust where roundcube unpacks everything.  Instead of unpacking everything into /var/www/html, roundcube could place its files into /var/www/html/$ROUNDCUBEMAIL_REQUEST_PATH.  

I was able to quickly test something similar by creating a symlink within the /var/www/html directory called roundcube.  This in turn made http://hostname.com/roundcube a valid path in apache's eyes, and everything now works correctly.  _(I'm not suggesting this symlink be the long term solution.)_
`docker exec roundcubemail ln -s /var/www/html /var/www/html/roundcube`

**Comment by pabzm** [comment]
Please explain more details, e.g. why you set ` ROUNDCUBEMAIL_REQUEST_PATH=/roundcube` in the first place.

Also please post your actual compose file and the relevant configs.

**Comment by zyberwoof** [comment]
I have roundcube setup behind a reverse proxy (Caddy).  And I have a domain name.  Let's pretend it is mydomain.com.  I am trying to make roundcube work at mydomain.com/roundcube.  I believe that is the purpose of changing ROUNDCUBEMAIL_REQUEST_PATH from it's default value of "/".

When I only set `ROUNDCUBEMAIL_REQUEST_PATH=/roundcube`, I cannot access roundcube at mydomain.com/roundcube.  But as soon as I run `docker exec roundcubemail ln -s /var/www/html /var/www/html/roundcube`, I can access the service at mydomain.com/roundcube.

docker-compose.yaml:
```
version: '2'

services:
  roundcubedb:
    image: mariadb
    container_name: roundcubedb
    restart: always
    ports:
      - 34010:5432
      - 33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  roundcubemail:
    image: roundcube/roundcubemail:latest-apache
    container_name: roundcubemail
    restart: always
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    ports:
      - 9002:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_NAME=${DB_NAME}
      - ROUNDCUBEMAIL_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=${DEFAULT_HOST}
      - ROUNDCUBEMAIL_SMTP_SERVER=${SMTP_SERVER}
      - ROUNDCUBEMAIL_IMAP_PORT=${IMAP_PORT}
      - ROUNDCUBEMAIL_SMTP_PORT=${SMTP_PORT}
      - ROUNDCUBEMAIL_REQUEST_PATH=/roundcube
      - ROUNDCUBEMAIL_USERNAME_DOMAIN=${USERNAME_DOMAIN}
```
