### ISSUE TITLE
How to get Roundcube web UI on port 443 with TLS for docker-compose-fpm.yaml ?

### ISSUE THREAD

**Issue by nupulu** [roundcube/roundcubemail-docker#302]
I have Roundcube running as container using the `docker-compose-fpm.yaml` example.
So far I got it all working apart from getting the Roundcube web UI on port 443 with TLS.

I enabled the correct port in the compose file and also mapped the letsencrypt file tree as described in the compose file, but it seems that the ngnix template `default.conf.template` does only provide plaintext UI on port 80.

```
  roundcubenginx:
    image: nginx:latest
    container_name: roundcubenginx
    # restart: unless-stopped
    ports:
      - '80:80'         # host:container
      - '443:443'       # host:container'
    depends_on:
      - roundcubemail
    links:
      - roundcubemail
    volumes:
      - ./www:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
      # Provide a custom nginx conf
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt

    environment:
      - NGINX_HOST=mail.mydomain.net  # set your local domain or your live domain
      - NGINX_PHP_CGI=roundcubemail:9000  # same as roundcubemail container name
```

What are further steps need to be taken to make nginx use port 443 for TLS with this container?
