### ISSUE TITLE
Latest image broken - static files in /var/www/html/public_html won't served

### ISSUE THREAD

**Issue by foorschtbar** [roundcube/roundcubemail-docker#326]
Since updating the container tonight to the latest apache image, Roundcube won't serve any static files:

```
roundcube-app        | xxx - - [26/Feb/2025:12:36:14 +0000] "GET / HTTP/1.0" 200 2934 "-" "xxx"
nginx-mailcow-1      | xxx - - [26/Feb/2025:13:36:14 +0100] "GET /rc/ HTTP/2.0" 200 2471 "-" "xxx"
roundcube-app        | [Wed Feb 26 12:36:14.170935 2025] [core:error] [pid 166:tid 166] [client xxx:50896] AH00037: Symbolic link not allowed or link target not accessible: /var/www/html/public_html/skins, referer: https://xxx
```

Maybe this had something to do with #321? I'm not sure if it's my setup or if the new image had a problem.

I can see that there a now symbolic links, but its disabled in apache config?

```
root@xxx:/var/www/html/public_html# ls -la
total 16
drwxrwxr-x  3 1000 1000 4096 May 19  2024 .
drwxr-xr-x 12 1000 1000 4096 Feb 14 02:00 ..
lrwxrwxrwx  1 1000 1000   12 May 19  2024 .htaccess -> ../.htaccess
-rw-rw-r--  1 1000 1000 1434 May 19  2024 index.php
lrwxrwxrwx  1 1000 1000   10 May 19  2024 plugins -> ../plugins
drwxrwxr-x  2 1000 1000 4096 May 19  2024 program
lrwxrwxrwx  1 1000 1000    8 May 19  2024 skins -> ../skins
```

**Comment by pabzm** [comment]
I can not reproduce that so far. Could you let me know:

* which container tools do you use?
* what are the image IDs and digests you are using?
* Do you mount any volumes?

**Comment by foorschtbar** [comment]
- roundcube/roundcubemail:latest (6b70a1a2e67b7f2cb54b011fe1b3aebf76695dc0b84d49a171eed27113f0a78f)
- compose file:
```yml
[...]
  roundcube-app:
    image: roundcube/roundcubemail
    container_name: roundcube-app
    restart: unless-stopped
    environment:
      - ROUNDCUBEMAIL_SKIN=elastic
[...]
    volumes:
      - ./volumes/roundcube/html:/var/www/html
      - ./volumes/roundcube/config/:/var/roundcube/config
    labels:
      # Watchtower
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - roundcube-db
    [...]
```
