### ISSUE TITLE
Consider to remove the code volume from examples

### ISSUE THREAD

**Issue by pabzm** [roundcube/roundcubemail-docker#337]
We currently use a bind-mount for the base directory in all our examples.

For ephemeral containers this should be only done if there's a good reason for it – which I don't see.

* Additional plugins could be mounted individually (or through a mounted `plugins/` directory at least).
* Additional config should be provided through mounting it to `/var/roundcube/config`, as we already suggest.

Additionally, depending on the platform, serving files from a mounted directory can be pretty slow.

@thomascube [explained](https://github.com/roundcube/roundcubemail-docker/issues/326#issuecomment-2807239901) the history of this case.

From that I figure that we should remove the bind-mounts for the base directory from all our examples. In the FPM-examples we can replace them with an "internal" (non-mounted) volume used by both containers.

Any thoughts?

**Comment by foorschtbar** [comment]
Yes, when the `html` (bind-)volume are not longer necessary (or was never), they can replaced in the examples with maybe:

```yml
[...]
volumes:
   - ./data/config/:/var/roundcube/config
   - ./data/plugins:/var/www/html/plugins
environment:
- ROUNDCUBEMAIL_COMPOSER_PLUGINS=roundcube/carddav
- ROUNDCUBEMAIL_PLUGINS=carddav
[...]
```
