### ISSUE TITLE
📨 Roundcube XOAUTH2 via Keycloak: Redirect Loop After Login (Dovecot Not Reached)

### ISSUE THREAD

**Issue by LiGo666** [roundcube/roundcubemail-docker#340]
Hi Roundcube community,

I'm currently building a modular, open-source, sovereign alternative to Microsoft 365 — a turnkey solution for organizations aiming to reclaim digital autonomy using self-hosted components. Roundcube is a key piece of this stack as the secure, web-based mail frontend.

The full stack includes:
- Traefik as reverse proxy with Let's Encrypt
- Keycloak for SSO and OAuth2/OIDC identity
- Nextcloud for groupware + file collaboration
- Dovecot as the IMAP backend
- Postfix for mail delivery
- Roundcube as the webmail interface
- WordPress and MediaWiki as additional SSO-integrated apps

I aim to keep each component as simple and modular as possible — avoiding solutions like Nextcloud AIO or full-stack mail bundles for now, in order to maintain a lean and transparent setup.

🎯 Objective
Enable XOAUTH2 login in Roundcube via Keycloak, where:

1. User logs in via Keycloak (OIDC)
2. Roundcube receives a token
3. Roundcube uses that token to authenticate to Dovecot using XOAUTH2 or OAUTHBEARER

❌ Current Issue
I’m stuck in a redirect loop between Roundcube and Keycloak:

- Keycloak completes authentication successfully
- Roundcube receives the OAuth2 code/token
- But instead of proceeding to the mailbox, it redirects again to /index.php/login/oauth
- This loops indefinitely
- Dovecot shows no incoming login attempt in its logs (auth_debug is on)
- Roundcube shows no clear error — the access token appears to be received properly

🕵️‍♂️ Assumptions & Checks
✅ Roundcube plugin oauth is enabled
✅ Keycloak client is configured with redirect URI https://webmail.example.org/index.php/login/oauth
✅ IMAP + SMTP host config points to valid SSL endpoints
✅ Token introspection and grant flows are working in isolated cURL tests
✅ Access tokens from Keycloak are valid and contain the email claim
✅ Roundcube is configured with:
- imap_auth_type = XOAUTH2
- smtp_auth_type = XOAUTH2
- oauth_identity_fields = ['email']

Yet Roundcube never proceeds to establish an IMAP connection, there is nothing in the dovecot logs.

🔐 Roundcube Config (anonymized config.inc.php)

```
$config['imap_host'] = 'ssl://mail.example.org:993';
$config['smtp_host'] = 'tls://mail.example.org:587';
$config['imap_auth_type'] = 'XOAUTH2';
$config['smtp_auth_type'] = 'XOAUTH2';
$config['oauth_provider'] = 'generic';
$config['oauth_provider_name'] = 'Keycloak';
$config['oauth_client_id'] = '***';
$config['oauth_client_secret'] = '***';
$config['oauth_auth_uri'] = 'https://auth.example.org/realms/default/protocol/openid-connect/auth';
$config['oauth_token_uri'] = 'https://auth.example.org/realms/default/protocol/openid-connect/token';
$config['oauth_identity_uri'] = 'https://auth.example.org/realms/default/protocol/openid-connect/userinfo';
$config['oauth_identity_fields'] = ['email'];
$config['oauth_scope'] = 'openid email profile';
$config['oauth_redirect_uri'] = 'https://webmail.example.org/index.php/login/oauth';
$config['oauth_login_redirect'] = true;
$config['oauth_use_refresh_tokens'] = true;
$config['plugins'] = ['oauth'];
$config['request_path'] = '/';
$config['use_https'] = true;
$config['debug_level'] = 1;
$config['imap_debug'] = true;
$config['smtp_debug'] = true;
```

🐳 Roundcube Docker Compose (anonymized)

```
services:
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    environment:
      - ROUNDCUBE_DEFAULT_HOST=ssl://mail.example.org
      - ROUNDCUBE_SMTP_SERVER=tls://mail.example.org
      - ROUNDCUBE_SMTP_PORT=587
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
    volumes:
      - ./config/:/var/www/html/config/:rw
      - roundcube_data:/var/roundcube
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.rule=Host(`webmail.example.org`)"
      - "traefik.http.routers.roundcube.entrypoints=websecure"
      - "traefik.http.routers.roundcube.tls.certresolver=letsencrypt"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
    networks:
      - proxy
      - default

volumes:
  roundcube_data:

networks:
  proxy:
    external: true
```

🔧 What I'm Looking For

- [ ] 1. Does Roundcube fully support using the OAuth2 access token to authenticate to IMAP via XOAUTH2?
- [ ] 2. Is there any required plugin config or hook I might be missing that passes the token to Dovecot?
- [ ] 3. Is this behavior known if the token can't be used or mapped?
- [ ] 4. How can I increase visibility into where the login flow stalls?

💡 Vision

My long-term goal is to build and maintain a fully open-source, Dockerized M365 alternative, and Roundcube plays a central role in the email layer. A functional XOAUTH2 setup is critical to achieving a unified identity experience across the stack.

Thank you for building and maintaining such an essential tool — any help, guidance, or pointers to working examples would be greatly appreciated!

Kind regards,
Christian
