### ISSUE TITLE
no roundcube:latest ?

### ISSUE THREAD

**Issue by hanscees** [roundcube/roundcubemail-docker#78]
Hi,

I am trying to find a usable roundcube:latest but it does not exist? 

I also tried to built the fpm-alpine version with a simple db but that failed horrible on multiple errors:

```
Creating roundcube ... done
Creating roundcubenginx ... error

ERROR: for roundcubenginx  Cannot create container for service roundcubenginx: source is not directory

ERROR: for roundcubenginx  Cannot create container for service roundcubenginx: source is not directory
ERROR: Encountered errors while bringing up the project.

```

A simple version without the heavy postgres would be appreciated, at least by me.
Below the docker-compose.yml I bravely attempted. 

```

#########################################
version: "2"

services:
  roundcube:
    build: ./
    container_name: roundcube
    #restart: always
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_DB_NAME=sqlite
      - ROUNDCUBEMAIL_DB_DIR:=/var/roundcube/db
    volumes
      - RC_config:/var/roundcube/config
      - RC_db:/var/roundcube/db
      - RC_HTML:/var/www/html
      - RC_tmp:/tmp/roundcube-temp


  roundcubenginx:
    image: nginx:latest
    container_name: roundcubenginx
    restart: always
    ports:
      - 80:80
      # If you need SSL connection
      # - '443:443'
    depends_on:
      - roundcube
    links:
      - roundcube
    volumes:
      - RC_HTML:/var/www/html
      #- /srv/roundcube/html:/var/www/html
      - NGINX_conf:/etc/nginx/nginx.conf:ro
      
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain

volumes:
  RC_config:
  RC_db:
  RC_HTML:
  RC_tmp:
  NGINX_conf:


```
